vimless: exit if $# = 0 and stdin is a tty

diff --git a/text/vimless/vimless b/text/vimless/vimless
--- a/text/vimless/vimless
+++ b/text/vimless/vimless
@@ -7,6 +7,14 @@
 
 LESS_N=""
 
+# Exit if no arguments were passed and stdin is attached to a tty
+if [ "$#" = "0" -a -t 0 ] ; then
+	echo "File argument[s] or stdin input required" 1>&2
+	echo "Usage: [command | ] $(basename "$0") [-N] [FILE...]" 1>&2
+	exit 1
+fi
+
+# XXX: right now, 'vimless -N FILE' is supported while 'vimless FILE -N' is not
 while getopts N f ; do
 	case "$f" in
 		N) LESS_N=1 ;;
