keepalive: add program name as prefix to logs

diff --git a/linux/keepalive/keepalive b/linux/keepalive/keepalive
--- a/linux/keepalive/keepalive
+++ b/linux/keepalive/keepalive
@@ -13,18 +13,16 @@
 # ps
 # xargs
 
+LOG_PREFIX="$(basename "$0"):"
+
 if [ "$#" = "0" ]; then
 	echo "No command line specified, exiting" 1>&2
 	echo "Usage: $(basename "$0") [PROGRAM] [ARGS...]" 1>&2
 	exit 1
 fi
 
-if [ "$(command -v "$1" 1>/dev/null 2>/dev/null ; echo $?)" != 0 ]; then
-	echo "Warning: executable \"$1\" not in \$PATH" 1>&2
-fi
-
 sigint_trap() {
-	echo "SIGINT received, exiting" 1>&2
+	echo "$LOG_PREFIX SIGINT received, exiting" 1>&2
 
 	JOBS="$(jobs -p)"
 
@@ -40,19 +38,25 @@ trap sigint_trap INT
 INTERVAL="${INTERVAL-10s}"
 INITIAL_SLEEP="${INITIAL_SLEEP-1s}"
 
+echo "$LOG_PREFIX polling interval $INTERVAL, initial sleep $INITIAL_SLEEP, process \"$1\", command line \"$*\"" 1>&2
+
+if [ "$(command -v "$1" 1>/dev/null 2>/dev/null ; echo $?)" != 0 ]; then
+	echo "$LOG_PREFIX warning: executable \"$1\" not in \$PATH" 1>&2
+fi
+
 sleep "$INITIAL_SLEEP"
 
 while true ; do
 	if [ "$(ps --no-headers -fC "$1" | wc -l)" = 0 ]; then
-		echo "$(date): restarting \"$*\"" 1>&2
+		echo "$LOG_PREFIX $(date): restarting \"$*\"" 1>&2
 		nohup -- "$@" 1>/dev/null 2>/dev/null &
 
 		{
-		sleep 1s
-		kill -0 "$!" 1>/dev/null 2>/dev/null
-		if [ "$?" != 0 ]; then
-			echo "Couldn't start \"$*\"" 1>&2
-		fi
+			sleep 1s
+			kill -0 "$!" 1>/dev/null 2>/dev/null
+			if [ "$?" != 0 ]; then
+				echo "$LOG_PREFIX error: couldn't start \"$*\"" 1>&2
+			fi
 		} &
 	fi
 
